### ISSUE TITLE
what's the password ?

### ISSUE THREAD

**Issue by burger456** [ExplorViz/frontend#1]
![图片](https://user-images.githubusercontent.com/43090300/200740724-5af4b8a3-27de-4808-bbb4-1f79f85f72b5.png)

**Comment by Alexander-Krause-Glau** [comment]
It should be "admin" and "password". However, this is the old version of ExplorViz. Which compose file are you starting? Follow the Getting started guide on https://explorviz.dev/1-getting-started/ to start the current version.

**Comment by burger456** [comment]
Thank you, I solved it❥
