### ISSUE TITLE
So..I have a new problem again, how do I create a new example?

### ISSUE THREAD

**Issue by burger456** [ExplorViz/frontend#2]
![图片](https://user-images.githubusercontent.com/43090300/200776559-02b3a799-d7ad-4464-bf4f-3f85e29aaf94.png)

**Comment by burger456** [comment]
I would really appreciate it if you could help me.
![图片](https://user-images.githubusercontent.com/43090300/200776876-ad459578-0c72-4ca5-ab9f-1db9e365bf16.png)

**Comment by Alexander-Krause-Glau** [comment]
There are two guides in getting started:

- quick start guide (that's the one that you started, it uses a mocked backend that has limited functionality, e.g., cannot add new software landscapes)
- [complex start guide](https://explorviz.dev/1-getting-started/#visualize-a-java-application) Here you will follow all steps to start the monitoring of a demo application that eventually results in a software visualization.

**Comment by burger456** [comment]
But after I run the example, I still can't find the program in the tool and it shows.
the .env
![图片](https://user-images.githubusercontent.com/43090300/200789032-6d9418ff-ba08-440b-aa4c-60dcd1f36511.png)
the ID and Secret.
![图片](https://user-images.githubusercontent.com/43090300/200789234-cf593336-c82f-4b21-a3bc-186ed45e276f.png)
the shows.
![图片](https://user-images.githubusercontent.com/43090300/200789454-9891ffe2-788d-4292-92b0-0546a5a7fb05.png)
the example run by docker
![图片](https://user-images.githubusercontent.com/43090300/200790354-06835fa0-139b-4e78-b01d-7eff084c396e.png)

**Comment by Alexander-Krause-Glau** [comment]
The guide mentions 

>  and generate some load by clicking around.

Click around in the PetClinic application. Does this help?

**Comment by burger456** [comment]
Sorry, this doesn't seem to work.
![图片](https://user-images.githubusercontent.com/43090300/200792045-19dd1c35-9f72-4765-b2e0-c69734890bbc.png)
![图片](https://user-images.githubusercontent.com/43090300/200792111-07509500-70ab-4fa0-8551-692226ead727.png)

**Comment by Alexander-Krause-Glau** [comment]
I just tested this and it works on my side. Try to

- pull new images , e.g. `docker compose pull`
- shutdown software stack and remove all volumes, e.g. `docker compose down -v` or `docker volume prune` (ATTENTION, this will remove all volumes in Docker)
- Restart stack

The log of the landscape-service should print out statements such as 
`2022-11-09 09:32:34,995 DEBUG [net.exp.lan.kaf.TopologyProducer] (executor-thread-1) Received 133 spans: 134 cached / already saved spans, 23 unknown / saved spans.` every tenth second. You can control that with `docker-compose logs -f`

**Comment by malte-hansen** [comment]
The [deployment repository](https://github.com/ExplorViz/deployment) as well as the corresponding [Getting Started Instructions](https://explorviz.dev/1-getting-started/) were recently updated. 

@burger456 Is your issue still present with the updated Docker configuration?

**Comment by malte-hansen** [comment]
I'm closing this issue as there hasn't been any activity on it for some time now. We assume that the issue has been resolved. 
If you believe that there's still something that needs to be done, please feel free to reopen the issue and let us know.
